language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="Django>=1.11,<2.0" DB=sqlite
  - DJANGO="Django>=2.0,<2.1" DB=sqlite
  - DJANGO="Django>=2.1,<2.2" DB=sqlite
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1" DB=sqlite
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2" DB=sqlite
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2" DB=sqlite
install:
  - export PYTHONPATH=./imagestore/:$PYTHONPATH
  - pip install $DJANGO
  - pip install -r test/testproject/requirements.txt
script:
  - python test/testproject/manage.py test imagestore
